apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
  namespace: postgres-lab
spec:
  description: Single PostgreSQL HA cluster for the lab
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie
  enableSuperuserAccess: false

  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  bootstrap:
    initdb:
      database: app
      owner: app
      encoding: UTF8
      localeCType: C
      localeCollate: C

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
    parameters:
      max_connections: "100"
      password_encryption: scram-sha-256

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  storage:
    storageClass: longhorn-postgres
    size: 5Gi
    resizeInUseVolumes: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-ha-backups
        serverName: postgres-ha-v1
